---
- name: System Configuration
  hosts: all
  tags:
    - config
    - system
  tasks:

    #- disable ssh
    #- name: SSH | check if remote login status is on
    #  sudo: yes
    #  command: systemsetup -getremotelogin
    #  register: remotelogin
    #  changed_when: "remotelogin.stdout.startswith('Remote Login: On') == True"

    #- name: SSH | disable remote login
    #  sudo: yes
    #  command: systemsetup -setremotelogin off
    #  when: remotelogin|changed

    # Enable the OSX default firewall
    # https://coderwall.com/p/zt8aqa
    #- name: System | enable firewall
    #  sudo: yes
    #  osx_defaults: domain=/Library/Preferences/com.apple.alf
    #                key=globalstate
    #                type=int
    #                value=1
      # notify: restart firewall

    # Note: due to Apple weirdness, this value is expected to be a string rather
    # then a bool, despite the fact it's a boolean value!, e.g. "true" as a str.
    - name: System | disable network .DS_Store
      osx_defaults: domain=com.apple.desktopservices
                    key=DSDontWriteNetworkStores
                    type=bool
                    value=true

    # TODO: check for full disk encryption! (maybe dont manually install)


    # TODO: set recovery message
    # # in case of lost device (yeah right)
    # # also gives my phone number to the entire interweb yay opensource
    # osx::recovery_message { 'If found, please call +1 5102067426': }
    # https://github.com/boxen/puppet-osx/blob/master/manifests/recovery_message.pp

  # handlers:
  #   - name: restart firewall
  #     sudo: yes
  #     shell: >
  #       launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
  #       launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist



#- name: Apps Setup
#  hosts: all
#  tasks:
#    - include: configs/divvy.yml    tags=divvy

- name: Apps/Interface Configuration
  hosts: all
  tags: interface

  tasks:
    #
    # Configuration related to the OSX Interface
    #
    - name: Interface | Mouse | tap to click
      osx_defaults: domain=com.apple.driver.AppleBluetoothMultitouch.trackpad
                    key=Clicking
                    type=bool
                    value=true
      # source: https://github.com/mathiasbynens/dotfiles/blob/master/.osx
      # echo "Set a shorter Delay until key repeat"
      # defaults write NSGlobalDomain InitialKeyRepeat -int 12
      # TODO: Disable auto-correct? https://gist.github.com/mbinna/2357277

    - name: Interface | Keyboard | keyboard repeat
      osx_defaults: domain=NSGlobalDomain
                    key=KeyRepeat
                    type=int
                    value=1

- name: Apps/GUI Configuration
  hosts: all
  tags: gui
  vars:
    dock:
      icon_size: 42

  tasks:
    #
    # Configuration related to the GUI
    #
    - name: UI | Dock | dim hidden apps
      osx_defaults: domain=com.apple.dock
                    key=showhidden
                    type=bool
                    value=true
      notify: killall Dock

    - name: UI | Dock | only show open apps
      osx_defaults: domain=com.apple.dock
                    key=static-only
                    type=bool
                    value=true
      notify: killall Dock

    - name: UI | Menu | battery percentage
      osx_defaults: domain=com.apple.menuextra.battery
                    key=ShowPercent
                    type=string
                    value=YES
      notify: killall Dock
      # source: https://github.com/josh-/dotfiles/blob/master/osx

    - name: UI | Dock | set icon size to {{ dock.icon_size }}
      osx_defaults: domain=com.apple.dock
                    key=tilesize
                    type=int
                    value={{ dock.icon_size }}
      # notify: killall Dock
      # TODO: need to fix integer value change check in osx_defaults script,
      # so this doesnt fire every time.

    - name: UI | Dock | enable auto-hide
      osx_defaults: domain=com.apple.dock
                    key=autohide
                    type=boolean
                    value=true
      notify: killall Dock

    - name: UI | Keyboard | enable full keyboard access
      osx_defaults: domain=NSGlobalDomain
                    key=AppleKeyboardUIMode
                    type=int
                    value=3
    
    - name: UI | Keyboard | Swap caps <-> command
      shell: hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x7000000E3}]}'

    - name: UI | Trackpad | enable tap to click
      osx_defaults: domain=com.apple.AppleMultitouchTrackpad
                    key=Clicking
                    type=int
                    value=1

    - name: UI | Trackpad | enable three-finger drag
      osx_defaults: domain=com.apple.AppleMultitouchTrackpad
                    key=TrackpadThreeFingerDrag
                    type=int
                    value=1

    - name: UI | Screensaver | bottom right hot corner
      osx_defaults: domain=com.apple.dock
                    key=wvous-br-corner
                    type=int
                    value=5
      notify: killall Dock

    - name: UI | Screensaver | bottom right hot corner mod
      osx_defaults: domain=com.apple.dock
                    key=wvous-br-modifier
                    type=int
                    value=0
      notify: killall Dock

    # - name: UI | Screensaver | Require password
    #   osx_defaults: domain=com.apple.screensaver
    #                 key=askForPassword
    #                 type=int
    #                 value=1
    #
    # - name: UI | Screensaver | Require password in 5 seconds
    #   osx_defaults: domain=com.apple.screensaver
    #                 key=askForPasswordDelay
    #                 type=int
    #                 value=5

    #
    # Configuration related to GUI apps
    #
    - name: Apps | Safari | enable Develop menu
      osx_defaults: domain=com.apple.safari
                    key=IncludeDevelopMenu
                    type=boolean
                    value=true

    - name: Apps | Safari | set cookie policy "Allow from current website only"
      osx_defaults: domain=com.apple.safari
                    key=BlockStoragePolicy
                    type=int
                    value=3

    - name: Apps | Safari | enable DoNotTrack header
      osx_defaults: domain=com.apple.safari
                    key=SendDoNotTrackHTTPHeader
                    type=boolean
                    value=true

    - name: Apps | Messages | save conversations on close
      osx_defaults: domain=com.apple.iChat
                    key=SaveConversationsOnClose
                    type=int
                    value=1
    
    - name: Apps | iTunes | don't autolaunch iTunes
      osx_defaults: domain=com.apple.iTunes
                    key=dontAutomaticallySyncIPods
                    type=boolean
                    value=true


    # TODO: install solarized theme for terminal.app
    # see https://github.com/mathiasbynens/dotfiles/blob/master/.osx
    # Documents to local disk by default: defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
    # Disable sleep completely: pmset -a sleep 0
    # OMG DID https://www.macissues.com/2015/01/15/sleep-and-power-settings-possibly-behind-wi-fi-dropouts-in-yosemite/ fix it?
    # pmset -b sleep 0
    # Tried this on my new laptop...let's see! It works!
    # Actually `-b` just does it for the battery, so need -a to do when on power
    #
    # VPN Settings
    #  security find-generic-password -a damon@simplymeasured.com -D "VPN Password" -g
    # http://www.proposedsolution.com/solutions/vpn-ipsec-prompting-saved-password/
    #
    # Also a good site w/settings: https://gist.github.com/tylerwalts/9375263
    #
    # And someday...replace Divvy: https://github.com/ashfinal/awesome-hammerspoon


  handlers:
    - name:    killall Finder
      command: killall Finder
    - name:    killall Dock
      command: killall Dock
    - name:    killall SystemUIServer
      command: killall SystemUIServer

    # - name: restart firewall
    #   sudo: yes
    #   shell: >
    #     launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
    #     launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist
