---
- name: set up sources
  hosts: all
  tags: casks
  sudo: false
  tasks:
  - name: get homebrew taps setup
    homebrew_tap: tap={{ item }} state=present
    always_run: yes
    with_items:
      - caskroom/cask
      - homebrew/binary
      - homebrew/versions

- name: essential tools for shell environment
  hosts: all
  tags: essential
  sudo: false
  tasks:
  - name: install essential shell brews
    homebrew: name={{ item }} state=present
    with_items:
      - git
      - hub
      - ssh-copy-id
      - imagemagick

  - name: remove legacy shell brews
    homebrew: name={{ item }} state=absent
    with_items:
      - gh #gh is now hub

  - name: install essential shell casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - xquartz


- name: Programming languages and environment platforms
  hosts: all
  tasks:
    #- include: tasks/go.yml      tags=go
    #  vars:
    #    gopath: ~/src/go

    - include: tasks/node.yml    tags=node
      vars:
        global_modules:
          - doctoc
          - ember-cli
        node_versions:
          - 0.10.29
          - 0.12.7
          - 4.3.2
          - 5.6.0

    - include: tasks/ruby.yml    tags=ruby
      vars:
        global_ruby: 2.2.1
        default_gems:
          - bundler
        rubies:
          - 1.9.3-p547
          - 1.9.3-p551
          - 2.1.5
          - 2.2.1


- name: Applications and tools
  hosts: all
  tasks:
  - name: install brewcask applications
    tags: casks
    homebrew_cask: state=present name={{ item }}
    with_items:
      # webdevs need all the webs (except opera lol)
      - google-chrome
      - firefox
      # text editors i hate the least
      - atom
      - sublime-text
      # virtual machine management
      - vagrant
      - virtualbox
      # other dev tools
      - hub
      - iterm2
      - java
      # analyst monster
      - sqlworkbenchj
      # non-dev stuff for general productivity
      - istat-menus
      - dropbox
      - flux
      - bartender
      - crashplan
      - divvy
      - 1password
      # bloated business shit
      - slack
      # non-dev stuff for general unproductivity
      - charles
      - cloak
      # - steam
      - spotify
      - sonos

  - name: install homebrew tools
    tags: brews
    homebrew: state=present name={{ item }}
    with_items:
      # dev tools
      - jq
      # - boot2docker
      # - docker
      # app engine
      - go-app-engine-64
      # heroku style development
      - heroku-toolbelt
      # - forego
      # networking tools
      - curl
      - wget
      - s3cmd
      - awscli
      # security tools
      - nmap
      # web dev
      - nginx
      - ngrok2
      # necessary for work things
      - mysql
      - postgres
      - cmake
      - libxml2
      - qt
      - maven
