---
- name: essential tools for shell environment
  hosts: all
  tags: essential
  sudo: false
  tasks:
  - name: install essential shell brews
    homebrew: name={{ item }} state=present
    loop:
      - git
      - hub

# More complex dev environments
- import_playbook: playbooks/development/node.yml
- import_playbook: playbooks/development/python.yml
- import_playbook: playbooks/development/vscode.yml
    
- name: Applications and tools
  hosts: all
  tasks:
  - name: install brewcask applications
    tags: casks
    homebrew_cask: state=present name={{ item }}
    with_items:
      # web browsers
      - google-chrome
      - firefox
      # for opening different urls in different browsers
      - finicky
      # vs code kind of guy
      - visual-studio-code
      # javaaaaaa
      - adoptopenjdk/openjdk/adoptopenjdk8
      - adoptopenjdk/openjdk/adoptopenjdk11
      - intellij-idea-ce
      # other dev tools
      - iterm2
      - homebrew/cask-fonts/font-fira-code
      # analyst monster
      - tableplus
      # non-dev stuff for general productivity
      - 1password
      - qbserve
      - istat-menus
      # non-dev stuff for general unproductivity
      - spotify
      # backups and offloaded storage
      - arq
      - dropbox
      # sharing localhost with others
      - ngrok

  - name: install homebrew tools
    tags: brews
    homebrew: state=present name={{ item }}
    with_items:
      # dev tools
      - jq
      - ripgrep
      - wget
      - awscli
      # shell tools
      - zsh-autosuggestions
      - zsh-syntax-highlighting
