---
- name: set up sources
  hosts: all
  tags: casks
  sudo: false
  tasks:
  - name: get homebrew taps setup
    homebrew_tap: tap={{ item }} state=present
    always_run: yes
    with_items:
      - caskroom/cask
      - homebrew/binary
      - homebrew/versions

  - name: get homebrew sources setup
    homebrew: name=brew-cask  state=present
    always_run: yes

- name: essential tools for shell environment
  hosts: all
  tags: essential
  sudo: false
  tasks:
  - name: install essential shell brews
    homebrew: name={{ item }} state=present
    with_items:
      - git
      - hub
      - ssh-copy-id
      - imagemagick

  - name: remove legacy shell brews
    homebrew: name={{ item }} state=absent
    with_items:
      - gh #gh is now hub

  - name: install essential shell casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - xquartz


- name: Programming languages and environment platforms
  hosts: all
  tasks:
    - include: tasks/go.yml      tags=go
      vars:
        gopath: ~/src/go

    - include: tasks/node.yml    tags=node
      vars:
        global_modules:
          - doctoc
          - ember-cli
        node_versions:
          - v0.10.29
          - v0.12.7

    - include: tasks/ruby.yml    tags=ruby
      vars:
        global_ruby: 2.2.1
        default_gems:
          - bundler
        rubies:
          - 1.9.3-p551
          - 2.1.5
          - 2.2.1


- name: Applications and tools
  hosts: all
  tasks:
  - name: install brewcask applications
    tags: casks
    homebrew_cask: state=present name={{ item }}
    with_items:
      # webdevs need all the webs (except opera lol)
      - google-chrome
      - firefox
      # text editors i hate the least
      - atom
      - sublime-text
      # - macvim
      # - mou
      # virtual machine management
      # - vmware-fusion
      # TODO: not currently doing any VM based development, reenable below when
      # doing so.
      # - vagrant
      - virtualbox
      # other dev tools
      # - dash
      - github
      - iterm2
      - java
      # non-dev stuff for general productivity
      # - caffeine
      # - cloud
      # - daisydisk
      - istat-menus
      - dropbox
      - flux
      - bartender
      - crashplan
      - divvy
      - 1password
      # - sizeup
      # bloated business shit
      - slack
      # - skype
      # - evernote #TODO possible to get rid of this bloated POS?
      # non-dev stuff for general unproductivity
      - charles
      # - steam
      - spotify
      - sonos
      # - transmission
      # - vlc

  - name: install homebrew tools
    tags: brews
    homebrew: state=present name={{ item }}
    with_items:
      # dev tools
      # - ack
      - jq
      # - gist
      - boot2docker
      - docker
      # app engine
      - go-app-engine-64
      # heroku style development
      - heroku-toolbelt
      # - forego
      # networking tools
      - curl
      - wget
      # - speedtest_cli
      # security tools
      # - gnupg
      - nmap
      # - pwgen
      # media related tools
      # - imagesnap
      # - pianobar
      # - ffmpeg
