---
- name: essential tools for shell environment
  hosts: all
  tags: essential
  sudo: false
  tasks:
  - name: install essential shell brews
    homebrew: name={{ item }} state=present
    with_items:
      - git
      - hub

# More complex dev environments
- import_playbook: playbooks/development/node.yml
- import_playbook: playbooks/development/python.yml
- import_playbook: playbooks/development/vscode.yml
    
- name: Applications and tools
  hosts: all
  tasks:
  - name: install brewcask applications
    tags: casks
    homebrew_cask: state=present name={{ item }}
    with_items:
      # webdevs need all the webs (except opera lol)
      - google-chrome
      - firefox
      # all of the text editors
      - sublime-text
      - visual-studio-code
      # javaaaaaa
      - intellij-idea-ce
      # virtual machine management
      - virtualbox
      # other dev tools
      - iterm2
      - font-fira-code
      - moreutils # isutf8 :)
      - parquet-tools
      - avro-tools
      # analyst monster
      - sqlworkbenchj
      # non-dev stuff for general productivity
      - hammerspoon
      - 1password
      - qbserve
      # non-dev stuff for general unproductivity
      - spotify
      # backups
      - arq
      # shell tools
      - zsh-autosuggestions
      - zsh-syntax-highlighting

  - name: install homebrew tools
    tags: brews
    homebrew: state=present name={{ item }}
    with_items:
      # dev tools
      - jq
      - ripgrep
      - python
      - python@2.5
      - wget
      - s3cmd
      - awscli
      - maven@3.5
