---
- name: Secret links that I don't want to put in dotfiles
  hosts: all

  tasks:
    - name: Dependent directories
      file:
        path: "/Users/{{ ansible_user_id }}/{{ item.dir }}"
        state: directory
        recurse: yes
      with_items:
        - { dir: '.aws' }
        - { dir: '.ssh' }

    - name: Config Files
      file:
        src: '/Users/{{ ansible_user_id }}/Dropbox/Settings/{{ item.src }}'
        dest: '/Users/{{ ansible_user_id }}/{{ item.dest }}'
        state: link
      with_items:
        - { src: 'gitconfig', dest: '.gitconfig' }
        - { src: 'id_rsa.greedv2', dest: '.ssh/id_rsa' }
        - { src: 'id_rsa.pub.greedv2', dest: '.ssh/id_rsa.pub' }
        - { src: 'aws_credentials', dest: '.aws/credentials' }
        - { src: 'aws_s3cfg', dest: '.s3cfg' }
