---
- name: configure shell environment for current user
  hosts: all
  gather_facts: yes
  tags: shell
  vars:
    desired_shell: /bin/zsh

  tasks:
    - name:     compare user current shell to {{ desired_shell }}
      shell:    dscl . -read ~ UserShell | awk '{print $2}'
      register: usershell
      changed_when: usershell.stdout != "{{ desired_shell }}"
      check_mode: no

    # Note: if make this sudo: yes, then playbook will require being run with
    # -K argument and password up front, but won't prompt user when changing
    # this step.
    - name:  change default shell to {{ desired_shell }}
      sudo:  yes
      shell: chsh -s {{ desired_shell }} {{ ansible_user_id }}
      when:  usershell|changed


#- name: dotfiles
#  hosts: all
#  gather_facts: yes
#  tags: dotfiles
#  tasks:
#    - name: dotfiles | cloned
#      git:  repo=git@github.com:{{ ansible_user_id }}/dotfiles.git
#            dest=~/.dotfiles
#            update=no
#            accept_hostkey=True
#      register: dotfiles_cloned
#
#    - name: dotfiles | force link if just first installed
#      when: dotfiles_cloned|changed
#      command: rake install
#      args:
#        chdir: ~/.dotfiles


- name: xtra placeholder (prevents error condition on --skip-tags=xtra)
  hosts: all
  gather_facts: no
  tags: xtra
  tasks:
    - debug: msg="nothing to see here, move along"
