---
- name: configure shell environment for current user
  hosts: all
  gather_facts: yes
  tags: shell
  vars:
    desired_shell: /bin/zsh
  tasks:
    - name: "set current user shell to {{ desired_shell }}"
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: "{{ desired_shell }}"


#- name: dotfiles
#  hosts: all
#  gather_facts: yes
#  tags: dotfiles
#  tasks:
#    - name: dotfiles | cloned
#      git:  repo=git@github.com:{{ ansible_user_id }}/dotfiles.git
#            dest=~/.dotfiles
#            update=no
#            accept_hostkey=True
#      register: dotfiles_cloned
#
#    - name: dotfiles | force link if just first installed
#      when: dotfiles_cloned|changed
#      command: rake install
#      args:
#        chdir: ~/.dotfiles


- name: xtra placeholder (prevents error condition on --skip-tags=xtra)
  hosts: all
  gather_facts: no
  tags: xtra
  tasks:
    - debug: msg="nothing to see here, move along"
