---

- name: install Go platform
  homebrew: name=go12 state=present install_options=with-cc-common

- name: install tools needed for `go get` to function as expected
  homebrew: name={{ item }} state=present
  with_items:
    - git
    - hg
    - bzr

- name: install additional Go tools
  command: go get {{ item }}
  environment:
    GOPATH:  "{{ gopath | expanduser }}"
  args:
    creates: "{{ gopath | expanduser }}/src/{{ item }}/"
  with_items:
    - golang.org/x/tools/cmd/godoc
    - golang.org/x/tools/cmd/vet
    - golang.org/x/tools/cmd/cover
    - github.com/tools/godep
    - github.com/bradfitz/goimports
