---
- name: Python Development Environment
  hosts: all
  tags: python
  vars:
    global_libraries:
      - virtualenv
      - flake8
      - pylint
      - gnureadline

  tasks:
    # we need to force always_run on this because otherwise the npm-tasks following
    # will barf in check-mode.
    - name: install Python3 platform
      homebrew: name=python state=present
      check_mode: false

    - name: install Python global dev tools but only for python3
      pip: state=present name={{ global_libraries }} executable=pip3
