---
- name: VSCode Development Environment
  hosts: all
  tags: vscode
  vars:
    extensions:
      - akamud.vscode-theme-onedark
      - akamud.vscode-theme-onelight
      - CoenraadS.bracket-pair-colorizer-2
      - eriklynd.json-tools
      - yzhang.markdown-all-in-one
      - jebbs.plantuml
      - ms-python.python
      - mechatroner.rainbow-csv
      - VisualStudioExptTeam.vscodeintellicode
      - adamhartford.vscode-base64

  tasks:
    - name: install vscode
      homebrew_cask: name=visual-studio-code state=present
      check_mode: false

    - name: gathering existing installed extensions
      shell: code --list-extensions
      register: currentextraw
      check_mode: false
      changed_when: false

    - set_fact:
        missing_extensions: "{{ extensions | difference(currentextraw.stdout_lines) }}"
        untracked_extensions: "{{ currentextraw.stdout_lines | difference(extensions) }}"

    - name: install missing extensions
      shell: code --install-extension {{item}}
      with_items: "{{ missing_extensions }}"

    # show us what we have installed that isn't managed here, in case we want to add it
    - debug: var=untracked_extensions